server:
  port: 8202

spring:
  application:
    name: THXU-Server-Test
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,com.baomidou.dynamic.datasource.spring.boot.autoconfigure.DynamicDataSourceAutoConfiguration
  boot:
    admin:
      client:
        url: http://localhost:8401
        username: thxu
        password: 123456
  zipkin:
    sender:
      type: rabbit
  sleuth:
    sampler:
      probability: 1
  rabbitmq:
    host: 192.168.10.100
    port: 5672
    username: thxu
    password: 123456

eureka:
  instance:
    #向Eureka 服务端发送心跳的间隔时间
    lease-renewal-interval-in-seconds: 20
  client:
    register-with-eureka: true
    fetch-registry: true
    instance-info-replication-interval-seconds: 30
    #默认值为30秒，即每30秒去Eureka服务端上获取服务并缓存，这里指定为3秒的原因是方便开发时测试，实际可以指定为默认值即可；
    registry-fetch-interval-seconds: 3
    serviceUrl:
      defaultZone: http://thxu:123456@localhost:8001/register/eureka/


security:
  oauth2:
    resource:
      id: ${spring.application.name}
      user-info-uri: http://localhost:8301/auth/user

#开启feign的回退功能
feign:
  hystrix:
    enabled: true

hystrix:
  shareSecurityContext: true

info:
  app:
    name: ${spring.application.name}
    description: "@project.description@"
    version: "1.0-SNAPSHOT"

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS